services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - social-multiplication-net

volumes:
  mysql-data:

networks:
  social-multiplication-net:
    driver: bridge
