server:
  port: 8000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: MULTIPLICATION-SERVICE
          uri: lb://MULTIPLICATION-SERVICE
          predicates:
            - Path=/api/v1/multiplication/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/