server:
  port: 8000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:9090'
            allowedHeaders:
              - '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
        - id: MULTIPLICATION-SERVICE
          uri: lb://MULTIPLICATION-SERVICE
          predicates:
            - Path=/api/v1/multiplication/**
          filters:
            - AuthenticationFilter
        - id: GAMIFICATION-SERVICE
          uri: lb://GAMIFICATION-SERVICE
          predicates:
            - Path=/api/v1/gamification/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/